### ISSUE TITLE
Differences between `xarray.resample().mean()` and `tc.average()`

### ISSUE THREAD

**Issue by andersy005** [coderepocenter/AxisUtilities#6]
I am noticing significant discrepancies between the output of `xarray.resample().mean()` and `tc.average()`. I expected the outputs of these two methods to be **numerically close**: 

![Screen Shot 2019-11-18 at 3 54 47 PM](https://user-images.githubusercontent.com/13301940/69101056-d3add100-0a1b-11ea-9090-11b7a60e3383.png)

Here's the full notebook: https://gist.github.com/andersy005/f33f5d4d7b55c6c2d350d84f6aec3028

Am I missing anything?

Cc @matt-long

**Comment by matt-long** [comment]
@andersy005, I find it odd that the min/max of the two computations are identical, but the mean and median are different. Are missing values being handled appropriately?  

I find that 
```python
>>> ds = xr.tutorial.load_dataset('rasm').Tair
>>> ds.min(), ds.max(), ds.mean(), ds.median()
(<xarray.DataArray 'Tair' ()>
 array(-46.30021934), <xarray.DataArray 'Tair' ()>
 array(37.42377999), <xarray.DataArray 'Tair' ()>
 array(-0.48212777), <xarray.DataArray 'Tair' ()>
 array(1.27951711))
```
which is identical to the results of your pandas approach. I would not expect a "resample" operation to change the mean, so that indicates that something is awry in the `axisutilities` approach.

**Comment by maboualidev** [comment]
@andersy005 @matt-long 
Hi,
I checked the code and there are couple of things going on.

Actually, the `xarray` calculation of weekly average is wrong.

### First, getting acquainted with the data
Issuing the following command:

```Python
ds = xr.tutorial.load_dataset('rasm').Tair
```
will end up loading a data set into `ds` with the shape of: `(time: 36, y: 205, x: 275)` where 

```
Coordinates:
  * time     (time) object 1980-09-16 12:00:00 ... 1983-08-17 00:00:00
```
Essentially the first element is associated to the middle of September 1980, the second element on time axis is associated to middle of October of 1980 and so on.

### What's going wrong?
#### (1) Wrong time axis is associated to original data set when using panda
The time coordinate of the data is overwritten with the following command:

```Python
ds["time"] = pd.date_range(start="1980-09-16 12:00:00", freq='1M', periods=36)
```
However, despite mentioning `start="1980-09-16 12:00:00"`, this is going to change the time axis to match the end of the month. Hence, now the first element of the data on time axis is associated to the end of September, (i.e. 1980-09-30), the second element to end of October, i.e. (1980-10-31), and so on.

#### (2) `resample` followed by `mean` shifts the data even further into future.
The following command:

```Python
ds_resampled = ds.resample(time='1W').mean()
```
is causing couple of issue. if you check the time-coordinate along with the time series values for, let's say, y=20, and x=200 here is what you get:

**ds_resampled time V.S. value for x=20, y=200 (only few items from the beginning is printed)**

time|value
-- | --
10/5/1980 | 8.43693162
10/12/1980 | nan
10/19/1980 | nan
10/26/1980 | nan
11/2/1980 | -2.25129301
11/9/1980 | nan
11/16/1980 | nan
11/23/1980 | nan

Now let's check what was the original data set for the same time period:

**ds, i.e. original data time V.S. value for x=20, y=200**

time|value
-- | --
9/16/1980 | 8.43693162
10/17/1980 | -2.25129301

as you can see the first data value, i.e. `8.43693162` which was originally associated to **Sep. 16th, 1980**, now is associated to the week of **Oct. 5th, 1980**. Likewise, the second data value, i.e. `-2.25129301` which was originally associated to **Oct. 17th, 1980** now is moved to **Nov. 2nd, 1980**.

####  (3) `resample` followed by `mean` produces a lot of `NaN`, where it shouldn't:

So, if you check the table above you would see that the `resample` followed by `mean` ends up to a lot of `NaN`:

time|value
-- | --
10/5/1980 | 8.43693162
10/12/1980 | nan
10/19/1980 | nan
10/26/1980 | nan
11/2/1980 | -2.25129301
11/9/1980 | nan
11/16/1980 | nan
11/23/1980 | nan

This is due to having a coarser time axis on the original data set and a finer time axis on the resampled data. We are going from monthly to weekly. the `xarray` `mean` does not really understands that the value associated to one month is value for the whole months. It thinks that the data is only valid for the date that is associated to it. For example, the first element, mistakenly was associated to Sep. 30th, 1980. After grouping using `resample(time='1W')`, everything within seven days are grouped together. Oct. 5th, 1980 is the first monday after Sep. 30th, 1980. So that week gets a value of `8.43693162`. But all the other weeks get nothing until the next week that overlaps with a data point. However, a monthly data is valid for the whole months.

`AxisUtility` is smarter about this, though. if you have a monthly data, and you go to weekly data, if a week is fully within that month, it would get the value of that month. we can do this because we have the concept of upper and lower bound in addition to data-tick concept in our model. 

If a week is split between two months, let's say, 2 days of it is in one month and 5 days of it is in another month, then that week average is 2/7 of the first month value and 5/7 of the second month value. This is more accurate calculations. 

Notice that `resample` + `mean` of xarray essentialy groups the numbers and then averages them. So in the similar case, this approach would weigh both month value the same and does not apportion it based on how many days of the week is actually in that months. `AxisUtilities` does this apportionment.

#### `AxisUtilities` Monthly Time Axis is missing the last day of the month:
This one is a bug in the `AxisUtilities`. When the monthly data is created it goes from the beginning of the first day of the month to the beginning of the last day of the month. For example, from Sep. 1st, 1980 12:00am to Sep. 30th, 1980, 12:00am. So, essentially it is forgetting the last day of each month. 
So, the `from_axis` created by:
```Python
from_axis = MonthlyTimeAxisBuilder(start_year=1980, start_month=9, end_year=1983, end_month=8).build()
```
is missing the last day of each months.

When creating the weekly axis using:

```Python
to_axis = WeeklyTimeAxisBuilder(start_date=date(1980, 9, 30), n_interval=153).build()
```
One might think that for example the first week, starting from Sep. 30th, 1980 is overlapping by the September month of 1980 in `from_axis`; But since `from_axis` is missing the last day of the month, the first week is not overlapping the first month; Hence, the first element of the original data set is not mapped and removed.

The fix is easy fortunately.

instead of 

```
date(y, m, monthrange(y, m)[1])
```

we need to do:

```
date(y, m, monthrange(y, m)[1]) + timedelta(days=1)
```

Hope this would help to understand what is going on. I think after fixing the last-day of the month issue in the `AxisUtilities` the result provided by `AxisUtilities` are actually more reliable than using `resample().mean()`

**Comment by matt-long** [comment]
Thanks @maboualidev. Does the bug fix enable recovering the straight-mean of the data, as I suggested it should above?

**Comment by maboualidev** [comment]
@matt-long I will check once I am back from SC19 conference; but I don’t think we would get the same number.

Note that ‘ds.mean’ weighs all values for each month equally. In axisconverter we are weighing each month according to their length. So the number in Feb. has a lower weight than the one in December.

Using ‘ds.resample.mean()’ significantly changes the area under the curve. Because a value that was assigned to a whole month is now assigned to only one week (which is also shifted a bit forward in time)

**Comment by maboualidev** [comment]
@matt-long @andersy005 Hi guys, I sent you an email with the comparison results. Please have a look and update me about what you think.

**Comment by maboualidev** [comment]
@matt-long @andersy005 based on our discussion yesterday and the data that was provided; I am assuming this issue is closed. I have also opened issue #8  for time unit conversion. Also issue #9 for raising error if the source and destination axis have different start and end.
